### ISSUE TITLE
I’m not even 21 yet

### ISSUE THREAD

**Issue by sylv256** [fabric-community/MCDrama#50]
![6F942846-755A-45D3-88A3-30ED3F2BE731](https://user-images.githubusercontent.com/18603248/125147682-d4b4da00-e0fa-11eb-8e61-a6aa48bf8d4a.jpeg)
wait that’s illegal

**Comment by valoeghese** [comment]
The legal drinking age in New Zealand is 18 so just assume it's in new zealand it's fine

**Comment by sylv256** [comment]
you think i'm 18? pathetic

**Comment by triangular2357** [comment]
in Germany it's 14 if your parents allow it

**Comment by Ueaj-Kerman** [comment]
in the god blessed United States of America it's any age if u don't get caught

**Comment by OakBricks** [comment]
what do you mean your not even 18 yet? i've been drinking hard liqour since the age of 12 smh
